'use strict';

// for user
export const CLEAN_ERROR='CLEAN_ERROR';
export const REQUEST_DOING="REQUEST_DOING";
export const REQUEST_DONE="REQUEST_DONE";
export const REQUEST_ERROR="REQUEST_ERROR";
export const REQUEST_SUCCESS="REQUEST_SUCCESS";
export const REQUEST_CLEAN="REQUEST_CLEAN";

export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
export const LOGGED_ERROR = 'LOGGED_ERROR';
export const LOGGED_DOING = 'LOGGED_DOING';

export const REGIST_DOING='REGIST_DOING';
export const REGIST_SUCCESS='REGIST_SUCCESS';
export const REGIST_FAILED='REGIST_FAILED';
export const REGIST_RESET='REGIST_RESET';

export const CLASS_GETALL_SUCCESS='CLASS_GETALL_SUCCESS';
export const CLASSES_SELECT_SUCCESS='CLASSES_REQUEST_SUCCESS';
export const CLASSES_ADD='CLASSES_REQUEST';
export const CLASSES_REMOVE='CLASSES_REMOVE';
export const CLASSES_USER_GET_SUCCESS='CLASSES_USER_GET_SUCCESS';
export const CLASSES_USER_DELETE_SUCCESS='CLASSES_USER_DELETE_SUCCESS';
export const CLASSES_USER_ADD_SUCCESS='CLASSES_USER_ADD_SUCCESS';

export const CLASSES_ADDHOMEWORK_SUCCESS="CLASSES_ADDHOMEWORK_SUCCESS";
export const CLASSES_REMOVEHOMEWORK_SUCCESS="CLASSES_REMOVEHOMEWORK_SUCCESS";
export const CLASSES_UPDATEHOMEWORK_SUCCESS="CLASSES_UPDATEHOMEWORK_SUCCESS";
export const CLASSES_GETHOMEWORK_SUCCESS="CLASSES_GETHOMEWORK_SUCCESS";
export const CLASSES_GETHOMEWORK_TODAY_SUCCESS="CLASSES_GETHOMEWORK_TODAY_SUCCESS";
export const CLASSES_GETSUBJECT_SUCCESS="CLASSES_GETSUBJECT_SUCCESS";
export const CLASSES_GETSTUDENTS_SUCCESS="CLASSES_GETSTUDENTS_SUCCESS";

export const CLASSES_GETINITDATA_SUCCESS="CLASSES_GETINITDATA_SUCCESS";

export const CLASSES_ADDNOTITY_SUCCESS="CLASSES_ADDNOTITY_SUCCESS";
export const CLASSES_UPDATENOTITY_SUCCESS="CLASSES_UPDATENOTITY_SUCCESS";
export const CLASSES_GETATENOTITY_SUCCESS="CLASSES_GETATENOTITY_SUCCESS";



